import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;

class AppLocalization {
  AppLocalization(this.locale);

  final Locale locale;

  static AppLocalization? of(BuildContext context) {
    return Localizations.of<AppLocalization>(context, AppLocalization);
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      "welcome": "Welcome",
      "no_product_at_cart": "You don't have any items in your cart",
      "login_to_your_account": "Login to your account",
      "enter_email": "Enter Email",
      "enter_password": "Enter password",
      "remember_me": "Remember me",
      "login": "Login",
      "one_time_password": "Enter the one-time password sent to your email",
      "search_category": "Search category",
      "search_product": "Search product",
      "color": "Color",
      "size": "Size",
      "standart": "Standart",
      "custom": "Custom",
      "add_to_cart": "Add to Cart",
      "your_preferences": "Your preferences",
      "cart": "Cart",
      "total": "Total",
      "subtotal": "Sub Total",
      "place_an_order": "Place an order",
      "client": "Client",
      "phone_number": "Phone number",
      "data": "Data",
      "full_name": "Full Name",
      "number": "Number",
      "address": "Address",
      "discount": "Discount",
      "next": "Next",
      "to_sum_it_up": "To sum it up",
      "submit_commercial": "Submit commercial",
      "print": "Print",
      "go_to_contract": "Go to contract",
      "print_contract": "Print contract",
      "commercial": "Commercial",
      "contract": "Contract",
      "sum": "sum",
      "client_not_found": "Client not found",
      "color_or_size_not_selected": "Color or size not selected",
      "client_added": "Client added",
      "client_changed_successfully": "Client changed successfully",
      "product_added_to_cart": "Product added to cart",
      "error_occurred": "Error occurred",
      "please_select_a_client": "Please select a client",
      "edit_client": "Edit Client",
      "add_client": "Add Client",
      "invoice_form": "Invoice Form",
      "offer_price_detail": "Offer Price Detail",
      "total_with_discount": "TOTAL WITHOUT DISCOUNT (VAT EXCLUDED)",
      "client_name": "Client name",
      "client_number": "Client number",
      "client_email": "Client email",
      "woiss_customer_representative_phone": "WOISS Customer Representative phone",
      "woiss_customer_representative_email": "WOISS Customer Representative e-mail",
      "propasal_date": "PROPOSAL DATE:",
      "estimated_production_time": "ESTIMATED PRODUCTION TIME (WEEK):",
      "offer_no": "OFFER NO:",
      "hall_vassari_living_area": "HALL VASSARI LIVING AREA",
      "picture": "PICTURE",
      "model": "MODEL",
      "product": "PRODUCT",
      "detail": "DETAIL",
      "price": "Price",
      "quantity": "Quantity",
      "total_price": "Total price",
      "sub_total_price": "SubTotal price",
      "do_you_want_to_print": "Do you want to print?",
      "log_out": "Log out",
      "log_message": "Are you sure you want to log out? This will delete all accounts in the branch",
      "this_contract_is_ready_for_printing": "This contract is ready for printing",
      "this_commercial_is_ready_for_printing": "This commercial is ready for printing",
      "yes": "Yes",
      "no": "No",
      "please_select_a_product": "Please select a product",
      "edit_commercial": "Edit Commercial",
      "edit_contract": "Edit Contract",
      "contract_is_edited": "Contract is edited",
      "commercial_is_edited": "Commercial is edited",
      "you_dont_have_any_commercials_yet": "You don't have any commercials yet",
      "you_dont_have_any_contracts_yet": "You don't have any contracts yet",
    },
    'ru': {
      "welcome": "Добро пожаловать",
      "no_product_at_cart": "У вас нет ни одного товара в корзине",
      "login_to_your_account": "Войдите в свой аккаунт",
      "enter_email": "Введите E-mail",
      "enter_password": "Введите пароль",
      "remember_me": "Запомнить меня",
      "login": "Войти",
      "one_time_password": "Введите OTP отправленный на почту",
      "search_category": "Поиск категории",
      "search_product": "Поиск товаров",
      "color": "Цвета",
      "size": "Размер",
      "standart": "Стандарт",
      "custom": "Под заказ",
      "add_to_cart": "Добавить в корзину",
      "your_preferences": "Ваши предпочтения",
      "cart": "Корзина",
      "total": "Итого",
      "subtotal": "Цена со скидкой",
      "place_an_order": "Разместить заказ",
      "client": "Клиент",
      "quantity": "Количество",
      "phone_number": "Номер телефона",
      "data": "Данные",
      "full_name": "Ф.И.О",
      "number": "Номер",
      "address": "Адрес",
      "discount": "Скидка",
      "next": "Cледующий",
      "price": "Цена",
      "to_sum_it_up": "Под итог",
      "submit_commercial": "Подать коммерческое",
      "print": "Распечатать",
      "go_to_contract": "Перейти к договору",
      "print_contract": "Распечатать договор ",
      "commercial": "Коммерческие",
      "contract": "Договора",
      "sum": "сум",
      "client_not_found": "Клиент не найден",
      "color_or_size_not_selected": "Цвет или размер не выбраны",
      "client_added": "Клиент добавлен",
      "client_changed_successfully": "Клиент успешно изменен",
      "product_added_to_cart": "Товар добавлен в корзину",
      "error_occurred": "Возникла ошибка",
      "please_select_a_client": "Пожалуйста выберите клиента",
      "edit_client": "Редактировать клиента",
      "add_client": "Добавить клиента",
      "do_you_want_to_print": "Хотите распечатать?",
      "log_out": "Выйти",
      "log_message": "Вы уверены, что хотите выйти? Это удалит все учетные записи в филиале",
      "this_contract_is_ready_for_printing": "Этот договор готов к печати",
      "this_commercial_is_ready_for_printing": "Это коммерчиское готово к печати",
      "yes": "Да",
      "no": "Нет",
      "please_select_a_product": "Пожалуйста, выберите продукт",
      "edit_commercial": "Изменить коммерческое",
      "edit_contract": "Изменить контракт",
      "contract_is_edited": "Контракт изменен",
      "commercial_is_edited": "Коммерческое изменен",
      "you_dont_have_any_commercials_yet": "У вас еще нет коммерческого предложения",
      "you_dont_have_any_contracts_yet": "У вас еще нет контрактов",
    },
    'tr': {
      'hello-world': 'Selam Dünya!',
      "welcome": "Hoş geldiniz",
      "no_product_at_cart": "Sepetinizde hiç ürün yok",
      "login_to_your_account": "Hesabınıza giriş yapın",
      "enter_email": "E-posta Girin",
      "enter_password": "Şifre girin",
      "remember_me": "Beni hatırla",
      "login": "Giriş yapmak",
      "one_time_password": "E-postanıza gönderilen tek kullanımlık şifreyi girin",
      "search_category": "Kategori ara",
      "search_product": "Ürün ara",
      "color": "Renk",
      "size": "Boyut",
      "standart": "Standart",
      "custom": "Őzel",
      "add_to_cart": "Sepete ekle",
      "your_preferences": "Tercihleriniz",
      "cart": "Sepet",
      "total": "Tutar",
      "subtotal": "İndirim",
      "quantity": "Adet",
      "place_an_order": "doğrulamak",
      "client": "Müşteri",
      "phone_number": "Telefon numarası",
      "data": "Müsteri",
      "full_name": "Ad Soyad",
      "number": "Telefon Numarasi",
      "address": "Adres",
      "discount": "İndirim oranı",
      "next": "Sonraki",
      "price": "Liste fiyati",
      "to_sum_it_up": "İndirimli fiyat",
      "submit_commercial": "Teklif formuna git",
      "print": "Yazdır",
      "go_to_contract": "Sözleşmeye git",
      "print_contract": "Sözleşmeyi yazdır",
      "commercial": "Teklif",
      "contract": "Sözleşme",
      "sum": "sum",
      "client_not_found": "Müşteri bulunamadı",
      "color_or_size_not_selected": "Renk veya boyut seçilmedi",
      "client_added": "Müşteri eklendi",
      "client_changed_successfully": "İstemci başarıyla değiştirildi",
      "product_added_to_cart": "Ürün sepete eklendi",
      "error_occurred": "Hata oluştu",
      "please_select_a_client": "Lütfen bir müşteri seçin",
      "edit_client": "Müşteri Bilgi Düzenle",
      "add_client": "Müşteri Ekle",
      "do_you_want_to_print": "Yazdırmak istiyor musunuz?",
      "log_out": "Çıkış Yap",
      "log_message": "Çıkış yapmak istediğinizden emin misiniz? Bu, şubedeki tüm hesapları siler",
      "this_contract_is_ready_for_printing": "Bu sőzleşme Baskiya Hazir",
      "this_commercial_is_ready_for_printing": "Bu invoice Baskiya Hazir",
      "yes": "Evet",
      "no": "Yok",
      "please_select_a_product": "Lütfen bir ürün seçin",
      "edit_commercial": "Sőzleşme değiştir",
      "edit_contract": "Invoice değiştir",
      "contract_is_edited": "Sözleşme düzenlendi",
      "commercial_is_edited": "Ticari düzenlenmiş",
      "you_dont_have_any_commercials_yet": "Henüz bir teklifiniz yok",
      "you_dont_have_any_contracts_yet": "Henüz sözleşmeniz yok",

    },
    'uz': {
      "welcome": "Xush kelibsiz",
      "no_product_at_cart": "Savatingizda biror tovar yo‘q",
      "login_to_your_account": "Hisobingizga kiring",
      "enter_email": "Email kiriting",
      "enter_password": "Parolni kiriting",
      "remember_me": "Eslab qolish",
      "login": "Kirish",
      "quantity": "Soni",
      "one_time_password": "Elektron pochtangizga yuborilgan bir martalik parolni kiriting",
      "search_category": "Category bo'yicha qidirish",
      "search_product": "Product bo'yicha qidirish",
      "color": "Rangi",
      "size": "O'lchami",
      "standart": "Standart",
      "custom": "Maxsus",
      "add_to_cart": "Savatchaga qo'shish",
      "your_preferences": "Sizning afzalliklaringiz",
      "cart": "Savatcha",
      "total": "Jami",
      "subtotal": "Chegirmali nax",
      "place_an_order": "Buyurtma bering",
      "client": "Klient",
      "phone_number": "Telefon nomer",
      "data": "Ma'lumotlar",
      "full_name": "F.I.SH",
      "number": "Nomer",
      "address": "Manzil",
      "discount": "Chegirma",
      "next": "Keyingisi",
      "price": "Narxi",
      "to_sum_it_up": "Pod Itog",
      "submit_commercial": "Kommersiyani yuborish",
      "print": "Chop etish",
      "go_to_contract": "Shartnomaga o'tish",
      "print_contract": "Shartnomaga chop etish",
      "commercial": "Kommersiya",
      "contract": "Shartnoma",
      "sum": "som",
      "client_not_found": "Mijoz topilmadi",
      "color_or_size_not_selected": "Rang yoki oʻlcham tanlanmagan",
      "client_added": "Mijoz qo'shildi",
      "client_changed_successfully": "Mijoz muvaffaqiyatli almashtirildi",
      "product_added_to_cart": "Mahsulot savatga qo'shildi",
      "error_occurred": "Xatolik yuz berdi",
      "please_select_a_client": "Iltimos client tanlang",
      "edit_client": "Klientni ozgartirish",
      "add_client": "Klient qoshish",
      "do_you_want_to_print": "Chop etishni xohlaysizmi?",
      "log_out": "Hisobdan chiqish",
      "log_message": "Rostdan ham hisobingizdan chiqmoqchimisiz? Bunda filialdagi barcha hisoblar o'chiriladi",
      "this_contract_is_ready_for_printing": "Ushbu shartnoma chop etishga tayyor",
      "this_commercial_is_ready_for_printing": "Ushbu kommersiya chop etishga tayyor",
      "yes": "Ha",
      "no": "Yoq",
      "please_select_a_product": "Iltimos, mahsulotni tanlang",
      "edit_commercial": "Tijoratni o'zgartiring",
      "edit_contract": "Shartnomani o'zgartirish",
      "contract_is_edited": "Shartnoma o'zgartirildi",
      "commercial_is_edited": "Tijorat o'zgartirildi",
      "you_dont_have_any_commercials_yet": "Sizda hali tijorat yo'q",
      "you_dont_have_any_contracts_yet": "Sizda hali kontrakt yo'q",
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]![key] ?? '** $key not found';
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<AppLocalization> {
  const AppLocalizationDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ru', 'tr', 'uz'].contains(locale.languageCode);

  @override
  Future<AppLocalization> load(Locale locale) {
    // Returning a SynchronousFuture here because an async "load" operation
    // isn't needed to produce an instance of DemoLocalizations.
    return SynchronousFuture<AppLocalization>(
      AppLocalization(locale),
    );
  }

  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
}
