name: furniture_app
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.1
  get: ^4.3.7
  provider: ^6.0.3
  shared_preferences: ^2.0.6
  easy_localization: ^3.0.0
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  syncfusion_flutter_pdf: ^20.2.45
  path_provider: ^2.0.11
  open_file: ^3.2.1
  sqflite: ^2.0.3+1

  pdf: ^3.8.3
  printing: ^5.9.2
  intl: ^0.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.10.0"
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  web:
    generate: true
    image_path: "assets/app_logo.png"
    windows:
      generate: true
      image_path: "assets/app_logo.png"
      icon_size: 48 # min:48, max:256, default: 48



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lang/
#    - assets/images/artur/
#    - assets/images/babylon/
#    - assets/images/kleo/


  fonts:
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant/Cormorant-Bold.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Medium.ttf
        - asset: assets/fonts/Cormorant/Cormorant-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif/NotoSerif-Bold.ttf
          weight: 700
    - family: Free-Sans
      fonts:
        - asset: assets/fonts/Free-Sans/FreeSansBold.ttf

